name = "PermuteArgs"
uuid = "9536dbe3-0ca9-4073-961c-7241c6d3471f"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "1.2.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Expronicon = "6b7a57c9-7cc1-4fdf-b7f5-e857abae3636"

[compat]
Combinatorics = "1"
Expronicon = "0.10.13"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
